[build]
builder = "NIXPACKS"

[build.nixpacks]
pkgs = ["python310", "gcc"]

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn tres_en_uno.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10